# Generated by Django 4.0.1 on 2022-01-29 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('teamids', models.TextField()),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('organisation', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('teams', models.TextField()),
                ('bugs', models.TextField()),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
