# Generated by Django 4.0.1 on 2022-01-29 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('bug', models.TextField()),
                ('mids', models.TextField()),
                ('password', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('teams', models.TextField()),
                ('tags', models.TextField()),
                ('visiblity', models.IntegerField()),
            ],
            options={
                'db_table': 'bugs',
                'managed': True,
            },
        ),
    ]
