# Generated by Django 4.0.1 on 2022-01-29 14:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_bugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('datetime', models.DateTimeField()),
                ('text', models.TextField()),
                ('updoots', models.IntegerField()),
                ('linkedto', models.TextField()),
                ('sender', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'messages',
                'managed': True,
            },
        ),
    ]
