# Generated by Django 4.0.1 on 2022-01-29 14:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50)),
                ('participantsid', models.TextField()),
                ('lead', models.CharField(max_length=255)),
                ('sdev', models.TextField()),
                ('jdev', models.TextField()),
            ],
            options={
                'db_table': 'teams',
                'managed': True,
            },
        ),
    ]
