# Generated by Django 4.0.1 on 2022-01-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_users_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
