# Generated by Django 4.0.1 on 2022-01-30 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_rename_firstname_users_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='userDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'details',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='users',
        ),
        migrations.RenameField(
            model_name='bugs',
            old_name='teams',
            new_name='reporter',
        ),
        migrations.RemoveField(
            model_name='bugs',
            name='company',
        ),
        migrations.RemoveField(
            model_name='bugs',
            name='password',
        ),
        migrations.RemoveField(
            model_name='bugs',
            name='phone',
        ),
    ]
