# Generated by Django 4.0.1 on 2022-01-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_bugs_date_created_bugs_date_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='is_dev',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='is_user',
        ),
        migrations.AddField(
            model_name='bugs',
            name='bug_title',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='date_created',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
