# Generated by Django 4.0.1 on 2022-01-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_userdetail_is_dev_remove_userdetail_is_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
