# Generated by Django 4.0.1 on 2022-01-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_bugs_bug_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
