# Generated by Django 4.0.1 on 2022-01-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_organisation_teams_software_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugs',
            old_name='bug_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='bugs',
            old_name='visiblity',
            new_name='visibility',
        ),
        migrations.AddField(
            model_name='bugs',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='status',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
