# Generated by Django 4.0.1 on 2022-01-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_bug_title_bugs_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='bug',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bugs',
            name='title',
            field=models.TextField(default='', max_length=500),
        ),
    ]
