# Generated by Django 4.0.1 on 2022-01-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_bugs_bug_alter_bugs_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='assignee',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bugs',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
