# Generated by Django 4.0.1 on 2022-01-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_bugs_assignee_bugs_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
