# Generated by Django 4.0.1 on 2022-01-30 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_bugs_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.teams'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='team',
            field=models.CharField(default='', max_length=255),
        ),
    ]
