# Generated by Django 4.0.1 on 2022-01-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_bugs_team_userdetail_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
