# Generated by Django 4.0.1 on 2022-01-30 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_teams_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugs',
            name='team',
        ),
    ]
